# Generated by Django 2.2.14 on 2020-08-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200825_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='education_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='workexperience_date',
            field=models.CharField(max_length=200),
        ),
    ]
