# Generated by Django 2.2.14 on 2020-08-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200825_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='additionalskills_text',
            new_name='additional_skills_text',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='additionalskills_title',
            new_name='additional_skills_title',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='workexperience_date',
            new_name='work_experience_date',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='workexperience_header',
            new_name='work_experience_header',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='workexperience_text',
            new_name='work_experience_text',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='workexperience_title',
            new_name='work_experience_title',
        ),
    ]
