# Generated by Django 2.2.14 on 2020-08-25 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200825_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='work_experience_date_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='work_experience_header_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='work_experience_text_2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
