# Generated by Django 2.2.14 on 2020-08-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200825_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='linked',
        ),
    ]
