# Generated by Django 2.2.14 on 2020-08-25 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_cv_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='../../static/images/'),
            preserve_default=False,
        ),
    ]
