# Generated by Django 2.2.14 on 2020-08-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_cv_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='profile_pic',
        ),
    ]
