# Generated by Django 2.2.14 on 2020-08-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_cv_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='additional_skills_title',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='education_title',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='profile_title',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='work_experience_title',
        ),
    ]
