# Generated by Django 2.2.14 on 2020-08-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200825_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='additional_skills_text',
            new_name='additional_skills_description',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='education_text',
            new_name='education_description',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='education_header',
            new_name='education_location',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='profile_text',
            new_name='professional_profile',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='work_experience_text',
            new_name='work_experience_description',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='work_experience_date_2',
            new_name='work_experience_location',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='work_experience_header',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='work_experience_header_2',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='work_experience_text_2',
        ),
    ]
