# Generated by Django 2.2.14 on 2020-08-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_cv_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='profile_picture',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='static/images/'),
        ),
    ]
