# Generated by Django 2.2.14 on 2020-08-28 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200828_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_experience_location', models.CharField(max_length=200)),
                ('work_experience_date', models.CharField(max_length=200)),
                ('work_experience_description', models.TextField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.CV')),
            ],
        ),
    ]
