# Generated by Django 2.2.14 on 2020-08-29 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200829_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='education_date',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='education_description',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='education_location',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_location', models.CharField(max_length=200)),
                ('education_date', models.CharField(max_length=200)),
                ('education_description', models.TextField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.CV')),
            ],
        ),
    ]
